### ISSUE TITLE
Centrum powiadomień

### ISSUE THREAD

**Issue by kabi097** [akai-org/newshub#24]
Implementacja prostego systemu powiadomień. Czyli jakaś ikonka z dzwoneczkiem, która po naciśnięciu rozwija listę z ostatnimi interakcjami użytkownika (np. Użytkownik xyg polubił twój komentarz). Fajnie byłoby znaleźć jakąś biblioteke JS do obsługi tego (od strony front-end'owej).
Od strony backendu wykorzystamy opisane w dokumentacji Laravela mechanizmy Events i Notifications.

**Comment by mozzar** [comment]
html/css
